### ISSUE TITLE
Скидка по имени, в определенные времена года.

### ISSUE THREAD

**Issue by leorossa** [leorossa/first_learn#12]
Покупатели регистрируя имя на специальной скидочной карте, заносятся в список и сортируются по алфавиту.
Далее весь список делится на четыре части(время года) и покупателям рассылается уведомление(на почту, телефон, else) о том что их ждет скидка на данный сезонный товар в связи с тем что данное имя олицетворяет это время года.

**Comment by cblp** [comment]
Это же идея программы? Что именно будет делать программа?

**Comment by leorossa** [comment]
сортировать, заносить в определенный список(сезон), и посылать уведомление. Остальное додумаю, но это хороший повод поработать с базами данных!

**Comment by cblp** [comment]
Понятно.

**Comment by leorossa** [comment]
Не справился

**Comment by cblp** [comment]
А почему закрыл? Больше не интересно?

**Comment by leorossa** [comment]
после того как посидел пару дней потупил в монитор, надо двинутся куда то и появилась работенка с сайтом на django. Там и базы данных и питон и вообще все.
