### ISSUE TITLE
Отступы перед и после функций

### ISSUE THREAD

**Issue by cblp** [leorossa/first_learn#3]
2 пустых строки

**Comment by leorossa** [comment]
Сделано.

**Comment by cblp** [comment]
Переоткрывай. После функции `discount_on_bus` не хватает отступа. Между шебангом и импортом тоже нужна одна строчка.

**Comment by cblp** [comment]
Переоткрывай. После функции discount_on_bus не хватает отступа.

**Comment by cblp** [comment]
Ладно, я выпишу новую карточку — #10
