### ISSUE TITLE
Раздели на две функции — ввод-вывод и вычисления

### ISSUE THREAD

**Issue by cblp** [leorossa/first_learn#6]
Сейчас одна функция делает слишком много — и ввод-вывод, и вычисления.

Сделай две. Пусть `discount_on_bus()` только вычисляет скидку, а, например, `main()` получает аргументы из командной строки, вызывает `discount_on_bus()` и печатает результат.

**Comment by leorossa** [comment]
попробую

**Comment by leorossa** [comment]
сделано

**Comment by cblp** [comment]
Не сделано. Продолжаем в #11
