### ISSUE TITLE
Нехорошо изменять аргументы командной строки

### ISSUE THREAD

**Issue by cblp** [leorossa/first_learn#7]
Лучше скопировать в переменную внутри функции, и новую переменную изменять.

@leorossa: А почему не хорошо и просто присвоить им значение?

@cblp: Потому что в достаточно большой программе ты можешь забыть, что изменял параметр, передать его в другую функцию, из другой в третью, а потом долго разбираться, почему программа себя ведёт не так, как указывает пользователь.

**Comment by leorossa** [comment]
как придать значение args.price переменной price.

**Comment by cblp** [comment]
`price = args.price`

**Comment by cblp** [comment]
Вообще, записать значение `y` в переменную `x` — это `x = y`, и если переменной такой не было, она будет создана.

**Comment by leorossa** [comment]
price, balancecard =main()

**Comment by cblp** [comment]
Продолжаем в #11

**Comment by cblp** [comment]
То есть эта проблема фактически решена, но плохо.
