### ISSUE TITLE
Некрасивые отступы

### ISSUE THREAD

**Issue by cblp** [leorossa/first_learn#8]
Либо первый аргумент в первой строке, а остальные под ним, и закрывать скобку вместе с последним аргументом (посмотри, как ты выше вызываешь `add_argument()` — там красиво)
```python
print("After 11 trips your balance has decreased by:"
      "{} with the new cost:"
      " {} you have enough on: {} travels."
      .format(args.balancecard, args.price, totaltrips))
```
либо отступ ровно в 4 позиции и закрывать скобку в той же позиции, с какой начинается строка, содержащая открывающую (мой любимый стиль)
```python
print(
    "After 11 trips your balance has decreased by:"
    "{} with the new cost:"
    " {} you have enough on: {} travels."
    .format(args.balancecard, args.price, totaltrips)
)
```

**Comment by leorossa** [comment]
сделано по первому примеру

**Comment by leorossa** [comment]
Сделано по первому примеру

**Comment by cblp** [comment]
OK
